# Managed by chezmoi.

# 让 tmux 用更匹配现代终端的 terminfo
set -g default-terminal "tmux-256color"

# (tmux 3.2+ 更推荐下面这行，若报错再删掉)
set -ga terminal-features ',xterm-256color:RGB'

# 更顺滑的交互
set -g mouse on
set -g focus-events on
